### ISSUE TITLE
[crossactivity] Unable to reach database

### ISSUE THREAD

**Issue by ZabeMath** [Pathoschild/Wikimedia-contrib#149]
Crossactivity doesn't work, it shows this:
```
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1049 Unknown database 'aawiki_p' in /data/project/meta2/git/wikimedia-contrib/tool-labs/backend/modules/Database.php:280 Stack trace: #0 /data/project/meta2/git/wikimedia-contrib/tool-labs/backend/modules/Database.php(280): PDO->query('use `aawiki_p`') #1 /data/project/meta2/git/wikimedia-contrib/tool-labs/backend/modules/Toolserver.php(89): Database->connect('s7.web.db.svc.e...', 'aawiki_p', NULL, NULL) #2 /data/project/meta2/git/wikimedia-contrib/tool-labs/crossactivity/index.php(86): Toolserver->connect('s7.web.db.svc.e...') #3 {main} thrown in /data/project/meta2/git/wikimedia-contrib/tool-labs/backend/modules/Database.php on line 280
```
Looks like #148, could it be that the fix hasn't been deployed to meta2?

**Comment by Pathoschild** [comment]
Yep. I just deployed the update to meta2 too; thanks for reporting it!
